### ISSUE TITLE
Stuck in for loop for certain multi-byte utf8 characters in an open quote

### ISSUE THREAD

**Issue by ghing** [creationix/jsonparse#17]
When a string in the JSON stream includes the "registered trademark" character (http://www.fileformat.info/info/unicode/char/00ae/index.htm), `Parser.write()` gets stuck in the for loop at https://github.com/creationix/jsonparse/blob/master/jsonparse.js#L96 indefinitely.  I believe that this is because `this.bytes_in_sequence` remains 0 in the code block starting at https://github.com/creationix/jsonparse/blob/master/jsonparse.js#L130

In the case of the "registered trademark" unicode, character, `n = 174`, so `this.bytes_in_sequence` remains `0` and `i` doesn't ever increase at https://github.com/creationix/jsonparse/blob/master/jsonparse.js#L142

Adding a line like:

```
        if ((n >= 128) && (n <= 193)) this.bytes_in_sequence = 1;
```

at around line 130 seemed to fix things for me.

I ran into this while using dominictarr/JSONStream.

**Comment by danpantry** [comment]
Voting to reopen due to http://stackoverflow.com/questions/32878450/node-js-infinite-loop-during-jsonstream/32996381#comment53837684_32996381: the issue is still prevalent and according to OP it occurs in later version as well?

A quick fix might be to ensure that no Unicode characters are passed to the stream, but something more permanent would be nice.

I'm not sure if you've fixed the issue in later releases, @creationix, but OP is using 0.0.5 which predates this issue.
